language: node_js
os:
 - linux
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
  - "4"

before_install:
  - 'nvm install-latest-npm'
install:
  - 'npm install'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4" ]; then npm install --no-save eslint@4 eslint-config-airbnb-base@13 ; elif [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm install --no-save eslint@5 ; fi'
  - 'npm ls > /dev/null'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run tests-only; fi'
sudo: false
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true

